version: "3"

services:

  selenium_hub:
    image: selenium/hub:3.14.0-gallium
    # depends_on:
    #   - deploy
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - qa_network
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 20
      GRID_TIMEOUT: 260000
      GRID_BROWSER_TIMEOUT: 180000
      SHM_SIZE: 512MB
      GRID_NEW_SESSION_WAIT_TIMEOUT: 260000

  selenium_firefox_node:
    image: selenium/node-firefox:3.14.0-gallium
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      FIREFOX_VERSION: 62.0.3
      SE_OPTS: -browser browserName=firefox,version=62.0.3,maxInstances=12,maxSessions=12
      NODE_MAX_INSTANCES: 12
      NODE_MAX_SESSION: 12
      SCREEN_WIDTH: 2560
      SCREEN_HEIGHT: 1440
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium_hub
    networks:
      - qa_network
    links:
      - selenium_hub:hub

  selenium_last_firefox_node:
    image: selenium/node-firefox:3.14.0-gallium
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      SE_OPTS: -browser browserName=firefox,version=61.0.2,maxInstances=4,maxSessions=4
      NODE_MAX_INSTANCES: 4
      NODE_MAX_SESSION: 4
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium_hub
    networks:
      - qa_network
    links:
      - selenium_hub:hub

  selenium_last_chrome_node:
    image: selenium/node-chrome:3.14.0-gallium
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      SE_OPTS: -browser browserName=chrome,version=68.0.3440.106,maxInstances=4,maxSessions=4
      SCREEN_WIDTH: 2560
      SCREEN_HEIGHT: 1440
      NODE_MAX_INSTANCES: 4
      NODE_MAX_SESSION: 4
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium_hub
    networks:
      - qa_network
    links:
      - selenium_hub:hub

  selenium_chrome_node:
    image: selenium/node-chrome:3.14.0-gallium
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      CHROME_VERSION: 69.0.3497.100
      SE_OPTS: -browser browserName=chrome,version=69.0.3497.100,maxInstances=12,maxSessions=12
      NODE_MAX_INSTANCES: 12
      NODE_MAX_SESSION: 12
      SCREEN_WIDTH: 2560
      SCREEN_HEIGHT: 1440
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium_hub
    networks:
      - qa_network
    links:
      - selenium_hub:hub

  owasp_zap_server:
    image: owasp/zap2docker-stable
    networks:
      - qa_network
    ports:
      - "8081:8081"
    command: zap.sh -daemon -port 8081 -host 0.0.0.0 -config api.key=0123456789 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config scanner.strength=INSANE


  lighthouse_server:
    image: kmturley/lighthouse-ci
    networks:
      - qa_network
    ports:
      - "8085:8085"


  analytics_test:
    build:
      context: ./qa
    depends_on:
      - selenium_chrome_node
    environment:
      HOST_URL: 'https://google.com'
      DRIVER: 'remote_ga_chrome'
      SELENIUM: 'http://selenium_hub:4444/wd/hub'
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
    volumes:
      - ./utilities/allure/allure_results:/usr/tmp/utilities/allure/allure_results:consistent
    networks:
      - qa_network
    command:
      bash -c './utilities/wait_for/wait-for-node.sh chrome:69.0.3497.100 --selenium_hub=selenium_hub -- behave -f allure_behave.formatter:AllureFormatter -o  utilities/allure/allure_results ./analytics/features'


  functional_current_chrome:
    build:
      context: ./qa
    depends_on:
      - selenium_chrome_node
    environment:
      HOST_URL: 'https://google.com'
      DRIVER: 'headless_chrome'
      SELENIUM: 'http://selenium_hub:4444/wd/hub'
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      TEST_RUNNER: 'Local'
      ENVIRONMENT_NAME: 'Production'
    volumes:
      - ./utilities/allure/allure_results:/usr/tmp/utilities/allure/allure_results:consistent
    networks:
      - qa_network
    command:
      bash -c './utilities/wait_for/wait-for-node.sh chrome:69.0.3497.100 --selenium_hub=selenium_hub -- behave -f allure_behave.formatter:AllureFormatter -o  utilities/allure/allure_results ./functional/features && echo -e "Test_Runner=${TEST_RUNNER}\nEnvironment=${ENVIRONMENT_NAME}" > utilities/allure/allure_results/environment.properties;'


  functional_last_chrome:
    build:
      context: ./qa
    depends_on:
      - selenium_last_chrome_node
    environment:
      HOST_URL: 'https://google.com'
      DRIVER: 'last_headless_chrome'
      SELENIUM: 'http://selenium_hub:4444/wd/hub'
    volumes:
      - ./utilities/allure/allure_results:/usr/tmp/utilities/allure/allure_results:consistent
    networks:
      - qa_network
    command:
      bash -c './utilities/wait_for/wait-for-node.sh chrome:68.0.3440.106 --selenium_hub=selenium_hub -- behave -f allure_behave.formatter:AllureFormatter -o  utilities/allure/allure_results ./functional/features'


  functional_current_firefox:
    build:
      context: ./qa
    depends_on:
      - selenium_firefox_node
    environment:
      HOST_URL: 'https://google.com'
      DRIVER: 'remote_firefox'
      SELENIUM: 'http://selenium_hub:4444/wd/hub'
    volumes:
      - ./utilities/allure/allure_results:/usr/tmp/utilities/allure/allure_results:consistent
    networks:
      - qa_network
    command:
      bash -c './utilities/wait_for/wait-for-node.sh firefox:62.0.3 --selenium_hub=selenium_hub -- behave -f allure_behave.formatter:AllureFormatter -o  utilities/allure/allure_results ./functional/features --no-skipped'


  functional_last_firefox:
    build:
      context: ./qa
    depends_on:
      - selenium_last_firefox_node
    environment:
      HOST_URL: 'https://google.com'
      DRIVER: 'last_remote_firefox'
      SELENIUM: 'http://selenium_hub:4444/wd/hub'
    volumes:
      - ./utilities/allure/allure_results:/usr/tmp/utilities/allure/allure_results:consistent
    networks:
      - qa_network
    command:
      bash -c './utilities/wait_for/wait-for-node.sh firefox:61.0.2 --selenium_hub=selenium_hub -- behave -f allure_behave.formatter:AllureFormatter -o  utilities/allure/allure_results ./functional/features --no-skipped'


  performance_tests:
    build:
      context: ./qa
    # depends_on:
      # - build
    environment:
      HOST_URL: 'https://google.com'
    volumes:
      - ./utilities/allure/allure_results:/usr/tmp/utilities/allure/allure_results:consistent
    networks:
      - qa_network
    command: bash -c 'set +e; python3 performance/only_locust_runner.py; set -e; behave -f allure_behave.formatter:AllureFormatter -o  utilities/allure/allure_results ./performance/features '


  visual_current_chrome:
    build:
      context: ./qa
    depends_on:
      - selenium_chrome_node
    environment:
      HOST_URL: 'http://testapp.galenframework.com'
      DRIVER: 'remote_ga_chrome'
    volumes:
      - ./utilities/allure/allure_results:/usr/tmp/utilities/allure/allure_results:consistent
    networks:
      - qa_network
    command:
      bash -c './utilities/wait_for/wait-for-node.sh chrome:69.0.3497.100 --selenium_hub=selenium_hub -- galen test visual/tests/ --config visual/docker_configs/current_remote_chrome.config --jsonreport visual/reports/ && behave -f allure_behave.formatter:AllureFormatter -o utilities/allure/allure_results/ visual/features/  --tags chrome-only --no-skipped'


  visual_last_chrome:
    build:
      context: ./qa
    depends_on:
      - selenium_last_chrome_node
    environment:
      HOST_URL: 'http://testapp.galenframework.com'
      DRIVER: 'remote_ga_chrome'
    volumes:
      - ./utilities/allure/allure_results:/usr/tmp/utilities/allure/allure_results:consistent
    networks:
      - qa_network
    command:
      bash -c './utilities/wait_for/wait-for-node.sh chrome:68.0.3440.106 --selenium_hub=selenium_hub -- galen test visual/tests/ --config visual/docker_configs/last_remote_chrome.config --jsonreport visual/reports/ && behave -f allure_behave.formatter:AllureFormatter -o utilities/allure/allure_results/ visual/features/  --tags chrome-only --no-skipped'


  visual_current_firefox:
    build:
      context: ./qa
    depends_on:
      - selenium_firefox_node
    environment:
      HOST_URL: 'http://testapp.galenframework.com'
      DRIVER: 'remote_firefox'
    volumes:
      - ./utilities/allure/allure_results:/usr/tmp/utilities/allure/allure_results:consistent
    networks:
      - qa_network
    command:
      bash -c './utilities/wait_for/wait-for-node.sh firefox:62.0.3 --selenium_hub=selenium_hub -- galen test visual/tests/ --config visual/docker_configs/current_remote_firefox.config --jsonreport visual/reports/ && behave -f allure_behave.formatter:AllureFormatter -o utilities/allure/allure_results/ visual/features/  --tags firefox-only --no-skipped'


  visual_last_firefox:
    build:
      context: ./qa
    depends_on:
      - selenium_last_firefox_node
    environment:
      HOST_URL: 'http://testapp.galenframework.com'
      DRIVER: 'remote_firefox'
    volumes:
      - ./utilities/allure/allure_results:/usr/tmp/utilities/allure/allure_results:consistent
    networks:
      - qa_network
    command:
      bash -c './utilities/wait_for/wait-for-node.sh firefox:61.0.2 --selenium_hub=selenium_hub -- galen test visual/tests/ --config visual/docker_configs/last_remote_firefox.config --jsonreport visual/reports/ && behave -f allure_behave.formatter:AllureFormatter -o utilities/allure/allure_results/ visual/features/  --tags firefox-only --no-skipped'


  security_tests:
    build:
      context: ./qa
    depends_on:
      - selenium_chrome_node
      - owasp_zap_server
    environment:
      HOST_URL: 'https://example.com'
      DRIVER: headless_chrome
      SELENIUM: http://selenium_hub:4444/wd/hub
      ZAP_ADDRESS: owasp_zap_server:8081
      ZAP_API_KEY: 0123456789
    volumes:
      - ./utilities/allure/allure_results:/usr/tmp/utilities/allure/allure_results:consistent
    networks:
      - qa_network
    command: bash -c './utilities/wait_for/wait-for --timeout=260 owasp_zap_server:8081 -- python3 security/docker_zap_scanner.py'

  # Need to figure out a wait for, for lighthouse
  # lighthouse_tests:
  #   build:
  #     context: ./qa
  #   depends_on:
  #     - lighthouse_server
  #   environment:
  #     HOST_URL: 'https://google.com'
  #     LIGHTHOUSE_IMAGE: 'lighthouse_server:8085'
  #   volumes:
  #     - ./utilities/allure/allure_results:/usr/tmp/utilities/allure/allure_results:consistent
  #   networks:
  #     - qa_network
  #   command:
  #     bash -c './utilities/wait_for/wait-for http://lighthouse_server:8085 -t 60  --   behave -f allure_behave.formatter:AllureFormatter -o  utilities/allure/allure_results ./accessibility/features'




networks:
  qa_network:
    driver: bridge

# volumes:
#   reports-volume
